export enum Tournament {
  RYUOU = '竜王戦',
  MEIJIN = '名人戦',
  RANK = '順位戦',
  EIOU = '叡王戦',
  OUI = '王位戦',
  OUZA = '王座戦',
  KISEI = '棋聖戦',
  KIOU = '棋王戦',
  OUSHO = '王将戦',
  ASAHI = '朝日杯将棋オープン戦',
  GINGA = '銀河戦',
  NHK = 'NHK杯',
  JT = '日本シリーズ',
  TATSUJIN = '達人戦',
  SINJIN = '新人王戦',
  KAKOGAWA = '加古川青流戦',
  ABEMA = 'AbemaTVトーナメント',
  SUNTORY = '将棋オールスター',
  HAKURAI = '白玲戦',
  F_RANK = '女流順位戦',
  SEIREI = '清麗戦',
  MAINABI = 'マイナビ女子',
  F_OUZA = '女流王座戦',
  F_MEIJIN = '女流名人戦',
  F_OUI = '女流王位戦',
  F_OUSHO = '女流王将戦',
  KURASHIKI = '倉敷藤花戦',
  HAKURYU = '白瀧あゆみ杯',
  KANSAI = '関西女流新鋭戦',
  ASAHI_AMA_MEIJIN = '朝日アマ名人戦',
  F_AMA_MEIJIN = '女流アマ名人戦',
  DENOU = '電王戦',
  HENNYU = '棋士編入試験',
  YAMADA = 'YAMADAチャレンジ杯'
}

export const TournamentList: { keys: string[], value: Tournament }[] = [

]
