export enum Tournament {
  RYUOU = '竜王戦',
  MEIJIN = '名人戦',
  RANK = '順位戦',
  EIOU = '叡王戦',
  OUI = '王位戦',
  OUZA = '王座戦',
  KISEI = '棋聖戦',
  KIOU = '棋王戦',
  OUSHO = '王将戦',
  ASAHI = '朝日杯将棋オープン戦',
  GINGA = '銀河戦',
  SHIN_GINGA = '新銀河戦',
  NHK = 'NHK杯',
  JT = '日本シリーズ',
  TATSUJIN = '達人戦',
  SINJIN = '新人王戦',
  KAKOGAWA = '加古川青流戦',
  JUDAN = '十段戦',
  SUNTORY = '将棋オールスター',
  HAKURAI = '白玲戦',
  F_RANK = '女流順位戦',
  SEIREI = '清麗戦',
  MAINABI = 'マイナビ女子オープン',
  F_OUZA = '女流王座戦',
  F_MEIJIN = '女流名人戦',
  F_OUI = '女流王位戦',
  F_OUSHO = '女流王将戦',
  F_SAIKYO = '女流最強戦',
  SAIKYO = '最強戦',
  KURASHIKI = '倉敷藤花戦',
  HAKURYU = '白瀧あゆみ杯',
  KANSAI = '関西女流新鋭戦',
  KANSAI_FEST = '関西女流棋士フェスタ',
  YAMADA = 'YAMADAチャレンジ杯',
  F_YAMADA = 'YAMADA女流チャレンジ杯',
  ABEMA = 'AbemaTVトーナメント',
  ABEMA_SPECIAL = 'AbemaTV特別企画',
  DENOU_TOURNAMENT = '電王トーナメント',
  SETAGAYA = '世田谷花みず木女流オープン',
  ASAHI_AMA_MEIJIN = '朝日アマ名人戦',
  F_AMA_MEIJIN = '女流アマ名人戦',
  NEXT_MOVE = '次の一手名人戦',
  MAINAVI_CHALLENGE = 'マイナビ・チャレンジマッチ',
  DENOU = '電王戦',
  HENNYU = '棋士編入試験',
  KEIKYU = '京急将棋まつり',
  TOKYU = '東急将棋まつり',
  TAKATSUKI = '高槻将棋まつり',
  TOCHIGI = 'とちぎ将棋まつり',
  JOSHU = '上州将棋祭り',
  GOMANGOKU = '五万石藤まつり',
  NEKOMADO = 'ねこまど将棋まつり',
  TENDO = '天童将棋祭り',
  TENDO_SAKURA = '天童桜まつり',
  YOKOHAMA = '横浜将棋まつり',
  SAIYUKI = '西遊棋'
}

// 大会名のリスト（検索用）
export const TournamentList: { keys: string[]; value: Tournament }[] = [
  { keys: ['朝日アマ名人戦', '朝日アマ'], value: Tournament.ASAHI_AMA_MEIJIN },
  { keys: ['女流アマ名人戦'], value: Tournament.F_AMA_MEIJIN },
  { keys: ['女流王座戦'], value: Tournament.F_OUZA },
  { keys: ['女流名人戦', '女流名人位'], value: Tournament.F_MEIJIN },
  { keys: ['女流王位戦'], value: Tournament.F_OUI },
  { keys: ['女流王将戦'], value: Tournament.F_OUSHO },
  { keys: ['女流順位戦'], value: Tournament.F_RANK },
  { keys: ['女流最強戦'], value: Tournament.F_SAIKYO },
  { keys: ['YAMADA女流チャレンジ杯'], value: Tournament.F_YAMADA },
  { keys: ['竜王戦'], value: Tournament.RYUOU },
  { keys: ['名人戦'], value: Tournament.MEIJIN },
  { keys: ['順位戦'], value: Tournament.RANK },
  { keys: ['叡王戦'], value: Tournament.EIOU },
  { keys: ['王位戦'], value: Tournament.OUI },
  { keys: ['王座戦'], value: Tournament.OUZA },
  { keys: ['棋聖戦'], value: Tournament.KISEI },
  { keys: ['棋王戦'], value: Tournament.KIOU },
  { keys: ['王将戦'], value: Tournament.OUSHO },
  { keys: ['朝日杯将棋オープン戦', '朝日杯'], value: Tournament.ASAHI },
  { keys: ['新銀河戦'], value: Tournament.SHIN_GINGA },
  { keys: ['銀河戦'], value: Tournament.GINGA },
  { keys: ['最強戦'], value: Tournament.SAIKYO },
  { keys: ['NHK杯'], value: Tournament.NHK },
  { keys: ['日本シリーズ'], value: Tournament.JT },
  { keys: ['達人戦'], value: Tournament.TATSUJIN },
  { keys: ['新人王戦'], value: Tournament.SINJIN },
  { keys: ['加古川青流戦'], value: Tournament.KAKOGAWA },
  { keys: ['ABEMAトーナメント', 'Abemaトーナメント', 'AbemaTVトーナメント'], value: Tournament.ABEMA },
  { keys: ['AbemaTV特別企画', 'AbemaTV新春女流企画'], value: Tournament.ABEMA_SPECIAL },
  { keys: ['将棋オールスター', 'SUNTORY東西対抗戦'], value: Tournament.SUNTORY },
  { keys: ['白玲戦'], value: Tournament.HAKURAI },
  { keys: ['清麗戦'], value: Tournament.SEIREI },
  { keys: ['マイナビ女子'], value: Tournament.MAINABI },
  { keys: ['倉敷藤花戦'], value: Tournament.KURASHIKI },
  { keys: ['白瀧あゆみ杯'], value: Tournament.HAKURYU },
  { keys: ['関西女流新鋭戦'], value: Tournament.KANSAI },
  { keys: ['電王戦'], value: Tournament.DENOU },
  { keys: ['編入試験'], value: Tournament.HENNYU },
  { keys: ['YAMADAチャレンジ杯'], value: Tournament.YAMADA },
  { keys: ['京急将棋まつり'], value: Tournament.KEIKYU },
  { keys: ['東急将棋まつり'], value: Tournament.TOKYU },
  { keys: ['高槻将棋まつり'], value: Tournament.TAKATSUKI },
  { keys: ['とちぎ将棋まつり'], value: Tournament.TOCHIGI },
  { keys: ['上州将棋祭り'], value: Tournament.JOSHU },
  { keys: ['五万石藤まつり'], value: Tournament.GOMANGOKU },
  { keys: ['電王トーナメント', '将棋電王'], value: Tournament.DENOU_TOURNAMENT },
  { keys: ['世田谷花みず木女流オープン', '花みず木'], value: Tournament.SETAGAYA },
  { keys: ['マイナビ・チャレンジマッチ'], value: Tournament.MAINAVI_CHALLENGE },
  { keys: ['十段戦'], value: Tournament.JUDAN },
  { keys: ['西遊棋'], value: Tournament.SAIYUKI },
  { keys: ['ねこまど将棋まつり'], value: Tournament.NEKOMADO },
  { keys: ['天童将棋祭り'], value: Tournament.TENDO },
  { keys: ['横浜将棋まつり'], value: Tournament.YOKOHAMA },
  { keys: ['関西女流棋士フェスタ'], value: Tournament.KANSAI_FEST },
  { keys: ['天童桜まつり'], value: Tournament.TENDO_SAKURA },
  { keys: ['次の一手名人戦'], value: Tournament.NEXT_MOVE }
]
